### ISSUE TITLE
Add Apprise Support

### ISSUE THREAD

**Issue by de0xy** [hotio/docker-restic#1]
It would be nice if the docker container supported [Apprise](https://github.com/caronc/apprise) for notifications. For example, a backup script might look like this:

```
export RESTIC_REPOSITORY='rest:http://localhost:8080/archive/'
export RESTIC_PASSWORD_FILE='/root/keyfile'
restic backup /mnt/user/archive \
  && apprise -t 'Restic' -b 'Backup was successful' \
  || apprise -t 'Restic' -b 'Backup Failed!'
```

Backups that fail silently can be deadly!

**Comment by hotio** [comment]
You make a good point, I'll add it....

**Comment by hotio** [comment]
Should be fixed with https://github.com/hotio/docker-restic/commit/edac311c7a1639cc994798ddd2c05e1090419f79
